[build]
  command = "npm install && npm run build:netlify"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/remote1/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/remote2/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
